package br.com.profitness.views;

import br.com.profitness.modelsCONEX.Conexao;
import com.br.profitness.modelsDAO.*;
import br.com.profitness.modelsBEANS.Instrutor;
import br.com.profitness.modelsBEANS.Tabela;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;


/**
 *
 * @author igorz
 */
public class FormInst extends javax.swing.JFrame {
    
    Instrutor mod = new Instrutor();
    DaoInstrutor con = new DaoInstrutor();
    Conexao conex = new Conexao();
    int flag = 0;
    
    
    

    /**
     * Creates new form FormProf
     */
    public FormInst() {
        initComponents();
        fillList("select * from instrutor order by nome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNovo = new javax.swing.JButton();
        jButtonGravar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelDados = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jLabelCEP = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelFone1 = new javax.swing.JLabel();
        jLabelFone2 = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jLabelRG = new javax.swing.JLabel();
        jLabelCREF = new javax.swing.JLabel();
        jLabelN = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabelEmail = new javax.swing.JLabel();
        jLabelDtNasc = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jTextFieldRG = new javax.swing.JTextField();
        jTextFieldCREF = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldN = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldEstado = new javax.swing.JTextField();
        jTextFieldFone1 = new javax.swing.JTextField();
        jTextFieldFone2 = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jLabelId_inst = new javax.swing.JLabel();
        jTextFieldId_inst = new javax.swing.JTextField();
        jDateChooserDt_nasc = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNomes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Instrutores");
        getContentPane().setLayout(null);

        jButtonNovo.setText("Incluir");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(20, 10, 61, 28);

        jButtonGravar.setText("Gravar");
        jButtonGravar.setEnabled(false);
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGravar);
        jButtonGravar.setBounds(140, 10, 64, 28);

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterar);
        jButtonAlterar.setBounds(240, 10, 63, 28);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(340, 10, 64, 28);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(450, 10, 90, 28);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(570, 10, 50, 28);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 40, 960, 20);

        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(10, 50, 280, 30);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(320, 50, 10, 460);

        jLabelDados.setText("Dados do Instrutor");
        getContentPane().add(jLabelDados);
        jLabelDados.setBounds(330, 50, 110, 16);

        jLabelNome.setText("Nome");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(400, 90, 60, 16);

        jLabelEndereco.setText("Endereço");
        getContentPane().add(jLabelEndereco);
        jLabelEndereco.setBounds(380, 280, 80, 16);

        jLabelBairro.setText("Brairro");
        getContentPane().add(jLabelBairro);
        jLabelBairro.setBounds(390, 330, 70, 16);

        jLabelCEP.setText("CEP");
        getContentPane().add(jLabelCEP);
        jLabelCEP.setBounds(400, 370, 50, 16);

        jLabelCidade.setText("Cidade");
        getContentPane().add(jLabelCidade);
        jLabelCidade.setBounds(390, 410, 80, 16);

        jLabelEstado.setText("UF");
        getContentPane().add(jLabelEstado);
        jLabelEstado.setBounds(700, 400, 20, 16);

        jLabelFone1.setText("Fone Res.");
        getContentPane().add(jLabelFone1);
        jLabelFone1.setBounds(380, 450, 100, 16);

        jLabelFone2.setText("Celular");
        getContentPane().add(jLabelFone2);
        jLabelFone2.setBounds(620, 450, 70, 16);

        jLabelCPF.setText("CPF");
        getContentPane().add(jLabelCPF);
        jLabelCPF.setBounds(410, 130, 50, 16);

        jLabelRG.setText("RG");
        getContentPane().add(jLabelRG);
        jLabelRG.setBounds(610, 130, 40, 16);

        jLabelCREF.setText("CREF");
        getContentPane().add(jLabelCREF);
        jLabelCREF.setBounds(400, 210, 70, 16);

        jLabelN.setText("Nº");
        getContentPane().add(jLabelN);
        jLabelN.setBounds(710, 280, 20, 16);

        jLabelSexo.setText("Sexo");
        getContentPane().add(jLabelSexo);
        jLabelSexo.setBounds(400, 240, 70, 16);

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----SELECIONE---\t", "Masculino", "Feminino" }));
        jComboBoxSexo.setEnabled(false);
        getContentPane().add(jComboBoxSexo);
        jComboBoxSexo.setBounds(450, 240, 130, 30);

        jLabelEmail.setText("Email");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(400, 490, 70, 16);

        jLabelDtNasc.setText("Data de Nasc");
        getContentPane().add(jLabelDtNasc);
        jLabelDtNasc.setBounds(360, 160, 110, 16);

        jTextFieldNome.setEnabled(false);
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(450, 80, 440, 30);

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.setEnabled(false);
        getContentPane().add(jFormattedTextFieldCPF);
        jFormattedTextFieldCPF.setBounds(450, 120, 120, 30);

        jTextFieldRG.setEnabled(false);
        getContentPane().add(jTextFieldRG);
        jTextFieldRG.setBounds(640, 120, 210, 30);

        jTextFieldCREF.setEnabled(false);
        getContentPane().add(jTextFieldCREF);
        jTextFieldCREF.setBounds(450, 200, 60, 30);

        jTextFieldEndereco.setEnabled(false);
        getContentPane().add(jTextFieldEndereco);
        jTextFieldEndereco.setBounds(450, 280, 250, 30);

        jTextFieldN.setEnabled(false);
        getContentPane().add(jTextFieldN);
        jTextFieldN.setBounds(730, 280, 50, 30);

        jTextFieldBairro.setEnabled(false);
        getContentPane().add(jTextFieldBairro);
        jTextFieldBairro.setBounds(450, 320, 130, 30);

        try {
            jFormattedTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCEP.setEnabled(false);
        getContentPane().add(jFormattedTextFieldCEP);
        jFormattedTextFieldCEP.setBounds(450, 360, 70, 30);

        jTextFieldCidade.setEnabled(false);
        getContentPane().add(jTextFieldCidade);
        jTextFieldCidade.setBounds(450, 400, 230, 30);

        jTextFieldEstado.setEnabled(false);
        jTextFieldEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEstado);
        jTextFieldEstado.setBounds(720, 400, 40, 30);

        jTextFieldFone1.setEnabled(false);
        getContentPane().add(jTextFieldFone1);
        jTextFieldFone1.setBounds(450, 440, 120, 30);

        jTextFieldFone2.setEnabled(false);
        getContentPane().add(jTextFieldFone2);
        jTextFieldFone2.setBounds(690, 440, 120, 30);

        jTextFieldEmail.setEnabled(false);
        getContentPane().add(jTextFieldEmail);
        jTextFieldEmail.setBounds(450, 480, 300, 30);

        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(290, 60, 40, 20);

        jLabelId_inst.setText("ID");
        getContentPane().add(jLabelId_inst);
        jLabelId_inst.setBounds(450, 50, 20, 16);

        jTextFieldId_inst.setEnabled(false);
        getContentPane().add(jTextFieldId_inst);
        jTextFieldId_inst.setBounds(470, 50, 60, 25);

        jDateChooserDt_nasc.setEnabled(false);
        getContentPane().add(jDateChooserDt_nasc);
        jDateChooserDt_nasc.setBounds(450, 160, 130, 30);

        jTableNomes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableNomes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNomesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableNomes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 300, 410);

        setSize(new java.awt.Dimension(999, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstadoActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed

        //campos obrigatorios
            if(jTextFieldNome.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Campo nome em branco, por favor preencha para continuar!");
                jTextFieldNome.requestFocus();
            }else if(jTextFieldCREF.getText().isEmpty()){
                
                JOptionPane.showMessageDialog(rootPane, "Campo CREF em branco, por favor preencha para continuar!");
                jTextFieldCREF.requestFocus();                
            }else if(jFormattedTextFieldCPF.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Campo CPF em branco, por favor preencha para continuar!");
                jFormattedTextFieldCPF.requestFocus();
            }else
        
        if(flag==1){
        mod.setNome(jTextFieldNome.getText());
        mod.setCpf(Integer.parseInt(jFormattedTextFieldCPF.getText()));
        mod.setRg(Integer.parseInt(jTextFieldRG.getText()));
        mod.setEmail(jTextFieldEmail.getText());
        mod.setCidade(jTextFieldCidade.getText());
        mod.setNumero(Integer.parseInt(jTextFieldN.getText()));
        mod.setBairro(jTextFieldBairro.getText());
        mod.setCep(Integer.parseInt(jFormattedTextFieldCEP.getText()));
        mod.setRua(jTextFieldEndereco.getText());
        mod.setEstado(jTextFieldEstado.getText());
        mod.setCref(jTextFieldCREF.getText());        
        mod.setDt_nasc(jDateChooserDt_nasc.getDate());
        mod.setTelefone(Integer.parseInt(jTextFieldFone1.getText()));
        mod.setCelular(Integer.parseInt(jTextFieldFone2.getText()));
        mod.setSexo(jComboBoxSexo.getSelectedItem().toString());
        //JOptionPane.showMessageDialog(rootPane,"cadastrou");        
        fillList("select * from instrutor order by nome");
        try {        
            con.salvar(mod);
            
                jTextFieldNome.setText("");
                jFormattedTextFieldCPF.setText("");
                jTextFieldRG.setText("");
                jTextFieldEmail.setText("");
                jTextFieldCidade.setText("");
                jTextFieldEndereco.setText("");
                jTextFieldN.setText("");
                jTextFieldBairro.setText("");
                jFormattedTextFieldCEP.setText("");
                jTextFieldEstado.setText("");
                jTextFieldCREF.setText("");
                jDateChooserDt_nasc.setDateFormatString("");
                jTextFieldFone1.setText("");
                jTextFieldFone2.setText("");
                jComboBoxSexo.setEnabled(false);
                jTextFieldNome.setEnabled(false);
                jFormattedTextFieldCPF.setEnabled(false);
                jTextFieldRG.setEnabled(false);
                jTextFieldEmail.setEnabled(false);
                jTextFieldEndereco.setEnabled(false);
                jTextFieldCidade.setEnabled(false);
                jTextFieldN.setEnabled(false);
                jTextFieldBairro.setEnabled(false);
                jFormattedTextFieldCEP.setEnabled(false);
                jTextFieldEstado.setEnabled(false);
                jTextFieldCREF.setEnabled(false);
                jDateChooserDt_nasc.setEnabled(false);
                jTextFieldFone1.setEnabled(false);
                jTextFieldFone2.setEnabled(false);
                jButtonGravar.setEnabled(false);
                
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"nao cadastrou"+ex);
        }
       } else{
            mod.setId_int((Integer.parseInt(jTextFieldId_inst.getText())));
           mod.setNome(jTextFieldNome.getText());
           
        mod.setCpf(Integer.parseInt(jFormattedTextFieldCPF.getText()));
        mod.setRg(Integer.parseInt(jTextFieldRG.getText()));
        mod.setEmail(jTextFieldEmail.getText());
        mod.setCidade(jTextFieldCidade.getText());
        mod.setNumero(Integer.parseInt(jTextFieldN.getText()));
        mod.setBairro(jTextFieldBairro.getText());
        mod.setCep(Integer.parseInt(jFormattedTextFieldCEP.getText()));
        mod.setRua(jTextFieldEndereco.getText());
        mod.setEstado(jTextFieldEstado.getText());
        mod.setCref(jTextFieldCREF.getText());        
        mod.setDt_nasc(jDateChooserDt_nasc.getDate());
        mod.setTelefone(Integer.parseInt(jTextFieldFone1.getText()));
        mod.setCelular(Integer.parseInt(jTextFieldFone2.getText()));
        mod.setSexo(jComboBoxSexo.getSelectedItem().toString());
        
            con.alterar(mod);
           //limpa os campos
            jTextFieldNome.setText("");
            jTextFieldCREF.setText("");
            jTextFieldEndereco.setText("");
            jTextFieldEmail.setText("");
            jTextFieldN.setText("");
            jTextFieldBairro.setText("");
            jTextFieldEstado.setText("");
            jTextFieldCidade.setText("");
            jTextFieldId_inst.setText("");
            jTextFieldFone1.setText("");
            jTextFieldFone2.setText("");
            jTextFieldRG.setText("");
            jFormattedTextFieldCEP.setText("");
            jFormattedTextFieldCPF.setText("");
            jDateChooserDt_nasc.setDateFormatString("");
            jComboBoxSexo.setSelectedItem("");
            //bloqueia campos/botoes
            jComboBoxSexo.setEnabled(false);
            jTextFieldNome.setEnabled(false);
            jFormattedTextFieldCPF.setEnabled(false);
            jTextFieldRG.setEnabled(false);
            jTextFieldEmail.setEnabled(false);
            jTextFieldEndereco.setEnabled(false);
            jTextFieldCidade.setEnabled(false);
            jTextFieldN.setEnabled(false);
            jTextFieldBairro.setEnabled(false);
            jFormattedTextFieldCEP.setEnabled(false);
            jTextFieldEstado.setEnabled(false);
            jTextFieldCREF.setEnabled(false);
            jDateChooserDt_nasc.setEnabled(false);
            jTextFieldFone1.setEnabled(false);
            jTextFieldFone2.setEnabled(false);
            jButtonGravar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            jButtonPesquisar.setEnabled(true);
            jTextFieldPesquisa.setEnabled(true);
            fillList("select * from instrutor order by nome");
        }
       
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jButtonGravar.setEnabled(true);
        jButtonAlterar.setEnabled(!true);
        jButtonExcluir.setEnabled(!true);
        jButtonCancelar.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        jTextFieldRG.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jTextFieldEndereco.setEnabled(true);
        jTextFieldN.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jFormattedTextFieldCEP.setEnabled(true);
        jTextFieldEstado.setEnabled(true);
        jTextFieldCREF.setEnabled(true);
        jDateChooserDt_nasc.setEnabled(true);
        jTextFieldFone1.setEnabled(true);
        jTextFieldFone2.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jButtonCancelar.setEnabled(true);
       
        //bloqueia os botoes
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
        jTableNomes.setEnabled(false);
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
        
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        
        mod.setPesquisa(jTextFieldPesquisa.getText());
        Instrutor busca = con.buscaInstrutor(mod);
        /*jTextFieldId_inst.setText(String.valueOf(busca.getId_int()));
        jTextFieldNome.setText(busca.getNome());
        jTextFieldCREF.setText(String.valueOf(busca.getCref()));
        jFormattedTextFieldCPF.setText(String.valueOf(busca.getCpf()));
        jTextFieldRG.setText(String.valueOf(busca.getRg()));
        jTextFieldEmail.setText(busca.getEmail());
        jTextFieldCidade.setText(busca.getCidade());
        jTextFieldEndereco.setText(busca.getRua());
        jTextFieldN.setText(String.valueOf(busca.getNumero()));
        jTextFieldBairro.setText(busca.getBairro());
        jFormattedTextFieldCEP.setText(String.valueOf(busca.getCep()));
        jTextFieldEstado.setText(busca.getEstado());
        jTextFieldCREF.setText(String.valueOf(busca.getCref()));
        jDateChooserDt_nasc.setDate(busca.getDt_nasc());
        jTextFieldFone1.setText(String.valueOf(busca.getTelefone()));
        jTextFieldFone2.setText(String.valueOf(busca.getCelular()));
        jComboBoxSexo.setSelectedItem(busca.getSexo());
        */
        fillList("select * from  instrutor where nome like '%"+mod.getPesquisa()+"%'");
        
        
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
          
        jButtonGravar.setEnabled(!true);
        jButtonAlterar.setEnabled(!false);
        jButtonExcluir.setEnabled(!true);
        jTextFieldNome.setEnabled(!true);
        jFormattedTextFieldCPF.setEnabled(!true);
        jTextFieldRG.setEnabled(!true);
        jTextFieldEmail.setEnabled(!true);
        jTextFieldCidade.setEnabled(!true);
        jTextFieldEndereco.setEnabled(!true);
        jTextFieldN.setEnabled(!true);
        jTextFieldBairro.setEnabled(!true);
        jFormattedTextFieldCEP.setEnabled(!true);
        jTextFieldEstado.setEnabled(!true);
        jTextFieldCREF.setEnabled(!true);
        jDateChooserDt_nasc.setEnabled(!true);
        jTextFieldFone1.setEnabled(!true);
        jTextFieldFone2.setEnabled(!true);
        jComboBoxSexo.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonGravar.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        //liberar os campos/botoes
        jTextFieldPesquisa.setEnabled(true);
        jButtonPesquisar.setEnabled(true);
        //limpa os campos
        jTextFieldNome.setText("");
        jTextFieldCREF.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldN.setText("");
        jTextFieldBairro.setText("");
        jTextFieldEstado.setText("");
        jTextFieldCidade.setText("");
        jTextFieldId_inst.setText("");
        jTextFieldFone1.setText("");
        jTextFieldFone2.setText("");
        jTextFieldRG.setText("");
        jFormattedTextFieldCEP.setText("");
        jFormattedTextFieldCPF.setText("");
        jDateChooserDt_nasc.setDateFormatString("");
        jComboBoxSexo.setSelectedItem("");
        
        
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        flag = 2;
        jButtonGravar.setEnabled(true);
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        jTextFieldRG.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jTextFieldEndereco.setEnabled(true);
        jTextFieldN.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jFormattedTextFieldCEP.setEnabled(true);
        jTextFieldEstado.setEnabled(true);
        jTextFieldCREF.setEnabled(true);
        jDateChooserDt_nasc.setEnabled(true);
        jTextFieldFone1.setEnabled(true);
        jTextFieldFone2.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        fillList("select * from instrutor order by nome");
        
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int respostausu = 0;
        respostausu = JOptionPane.showConfirmDialog(rootPane,"Realemte deseja apagar instrutor?");
            if(respostausu == JOptionPane.YES_OPTION){
                mod.setId_int(Integer.parseInt(jTextFieldId_inst.getText()));
                con.excluir(mod);
                
                    jTextFieldId_inst.setText("");
                    jTextFieldNome.setText("");
                    jTextFieldCREF.setText("");
                    jTextFieldPesquisa.setText("");            
                    jComboBoxSexo.setEnabled(false);
                    jTextFieldNome.setEnabled(false);
                    jFormattedTextFieldCPF.setEnabled(false);
                    jTextFieldRG.setEnabled(false);
                    jTextFieldEmail.setEnabled(false);
                    jTextFieldEndereco.setEnabled(false);
                    jTextFieldCidade.setEnabled(false);
                    jTextFieldN.setEnabled(false);
                    jTextFieldBairro.setEnabled(false);
                    jFormattedTextFieldCEP.setEnabled(false);
                    jTextFieldEstado.setEnabled(false);
                    jTextFieldCREF.setEnabled(false);
                    jDateChooserDt_nasc.setEnabled(false);
                    jTextFieldFone1.setEnabled(false);
                    jTextFieldFone2.setEnabled(false);
                    jButtonGravar.setEnabled(false);
                    jButtonNovo.setEnabled(true);
                    jButtonCancelar.setEnabled(false);
                    jButtonAlterar.setEnabled(false);
                    fillList("select * from instrutor order by nome");
            }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableNomesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNomesMouseClicked
        String nome = ""+jTableNomes.getValueAt(jTableNomes.getSelectedRow(),1);
        conex.conecta();
            conex.executaSQL("select * from instrutor where nome='"+nome+"'");
        try {
            conex.rs.first();
               jTextFieldId_inst.setText(String.valueOf(conex.rs.getInt("id_inst")));
               jTextFieldNome.setText(conex.rs.getString("nome"));
               jTextFieldCREF.setText(String.valueOf(conex.rs.getInt("cref")));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro"+ex);
        }
           
        conex.desconecta();
        
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        
    }//GEN-LAST:event_jTableNomesMouseClicked
//mostra os nomes dos instrutores q estão no bd na lista do formulário
       public void fillList(String Sql){
            ArrayList inf = new ArrayList();
            String [] columns = new String []{"ID", "Nome", "CREF"};
                conex.conecta();
                    conex.executaSQL(Sql);
                    
                    try{
                        conex.rs.first();
                        do{
                            inf.add(new Object[]{conex.rs.getInt("id_inst"), conex.rs.getString("nome"), conex.rs.getInt("cref")});
                            
                        }while(conex.rs.next());
                    }catch (SQLException ex){
                        JOptionPane.showMessageDialog(rootPane,"Nome "+mod.getPesquisa()+" não encontrado, tente novamente!");
                    }
                    
                    Tabela modTable = new Tabela(inf, columns);
                        jTableNomes.setModel(modTable);                        
                        jTableNomes.getColumnModel().getColumn(0).setPreferredWidth(34);
                        jTableNomes.getColumnModel().getColumn(0).setResizable(false);
                        jTableNomes.getColumnModel().getColumn(1).setPreferredWidth(200);
                        jTableNomes.getColumnModel().getColumn(1).setResizable(false);
                        jTableNomes.getColumnModel().getColumn(2).setPreferredWidth(60);
                        jTableNomes.getColumnModel().getColumn(2).setResizable(false);
                        jTableNomes.getTableHeader().setReorderingAllowed(false);
                        jTableNomes.setAutoResizeMode(jTableNomes.AUTO_RESIZE_OFF);
                        jTableNomes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);                      
                
                
                conex.desconecta();
        }
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInst().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private com.toedter.calendar.JDateChooser jDateChooserDt_nasc;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCREF;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelDados;
    private javax.swing.JLabel jLabelDtNasc;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFone1;
    private javax.swing.JLabel jLabelFone2;
    private javax.swing.JLabel jLabelId_inst;
    private javax.swing.JLabel jLabelN;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableNomes;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCREF;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldFone1;
    private javax.swing.JTextField jTextFieldFone2;
    private javax.swing.JTextField jTextFieldId_inst;
    private javax.swing.JTextField jTextFieldN;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldRG;
    // End of variables declaration//GEN-END:variables
}
