/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.profitness.views;

import br.com.profitness.modelsCONEX.Conexao;
import com.br.profitness.modelsDAO.DaoUsuario;
import br.com.profitness.modelsBEANS.Usuarios;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author igorz
 */
public class FormUsu extends javax.swing.JFrame {
    
    Usuarios mod = new Usuarios();
    DaoUsuario con = new DaoUsuario();
    Conexao conex = new Conexao();
    int flag = 0;
    
    
    

    /**
     * Creates new form FormProf
     */
    public FormUsu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNovo = new javax.swing.JButton();
        jButtonGravar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jScrollPaneNomes = new javax.swing.JScrollPane();
        jListNomes = new javax.swing.JList<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelDados = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jLabelId_inst = new javax.swing.JLabel();
        jTextFieldId_Usu = new javax.swing.JTextField();
        jTextFieldSenha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonNovo.setText("Incluir");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(20, 10, 61, 23);

        jButtonGravar.setText("Gravar");
        jButtonGravar.setEnabled(false);
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGravar);
        jButtonGravar.setBounds(140, 10, 65, 23);

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterar);
        jButtonAlterar.setBounds(240, 10, 65, 23);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(340, 10, 63, 23);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(450, 10, 90, 23);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(570, 10, 51, 23);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 40, 910, 20);

        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(10, 50, 280, 30);

        jListNomes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneNomes.setViewportView(jListNomes);

        getContentPane().add(jScrollPaneNomes);
        jScrollPaneNomes.setBounds(10, 100, 280, 100);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(300, 50, 10, 150);

        jLabelDados.setText("Dados do Usuário");
        getContentPane().add(jLabelDados);
        jLabelDados.setBounds(310, 50, 110, 14);

        jLabelNome.setText("Nome");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(380, 90, 60, 14);

        jLabelSenha.setText("Senha");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(390, 130, 50, 14);

        jTextFieldNome.setEnabled(false);
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(430, 80, 120, 30);

        jButtonPesquisar.setText("jButton1");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(240, 80, 40, 10);

        jLabelId_inst.setText("ID");
        getContentPane().add(jLabelId_inst);
        jLabelId_inst.setBounds(430, 50, 20, 14);

        jTextFieldId_Usu.setEnabled(false);
        getContentPane().add(jTextFieldId_Usu);
        jTextFieldId_Usu.setBounds(450, 50, 60, 25);

        jTextFieldSenha.setEnabled(false);
        getContentPane().add(jTextFieldSenha);
        jTextFieldSenha.setBounds(430, 130, 110, 30);

        setSize(new java.awt.Dimension(658, 225));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed

        if(flag==1){
        mod.setNome(jTextFieldNome.getText());
        mod.setSenha(jTextFieldSenha.getText());
       
        JOptionPane.showMessageDialog(rootPane,"cadastrou");        
        try {        
            con.salvar(mod);
            
                jTextFieldNome.setText("");
                jTextFieldSenha.setText("");
                
                jTextFieldNome.setEnabled(false);
                jTextFieldSenha.setEnabled(false);
                jButtonGravar.setEnabled(false);
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"nao cadastrou"+ex);
        }
       } else{
            mod.setId_usu((Integer.parseInt(jTextFieldId_Usu.getText())));
            mod.setNome(jTextFieldNome.getText());
            mod.setSenha(jTextFieldSenha.getSelectedText());
            con.alterar(mod);
            //limpar campos
            jTextFieldId_Usu.setText("");
            jTextFieldNome.setText("");  
            jTextFieldSenha.setText("");
            jTextFieldPesquisa.setText("");     
            jTextFieldNome.setEnabled(false);           
            jButtonGravar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            
        }
       
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jButtonGravar.setEnabled(true);
        jButtonAlterar.setEnabled(!true);
        jButtonExcluir.setEnabled(!true);
        jButtonCancelar.setEnabled(true);
        jTextFieldNome.setEnabled(true);   
        jTextFieldSenha.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
        
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        
        mod.setPesquisa(jTextFieldPesquisa.getText());
        Usuarios busca = con.buscaUsuarios(mod);
        jTextFieldId_Usu.setText(String.valueOf(busca.getId_usu()));
        jTextFieldNome.setText(busca.getNome());      
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
          
        jButtonGravar.setEnabled(!true);
        jButtonAlterar.setEnabled(!false);
        jButtonExcluir.setEnabled(!true);
        jTextFieldNome.setEnabled(!true);     
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonGravar.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        flag = 2;
        jButtonGravar.setEnabled(true);
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jTextFieldNome.setEnabled(true);        
        jButtonCancelar.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int respostausu = 0;
        respostausu = JOptionPane.showConfirmDialog(rootPane,"Realemte deseja apagar usuario?");
            if(respostausu == JOptionPane.YES_OPTION){
                mod.setId_usu(Integer.parseInt(jTextFieldId_Usu.getText()));
                con.excluir(mod);
                
                    jTextFieldId_Usu.setText("");
                    jTextFieldNome.setText("");
                    jTextFieldSenha.setText("");
                    jTextFieldPesquisa.setText("");                                
                    jTextFieldNome.setEnabled(false);                    
                    jTextFieldSenha.setEnabled(false);
                    jButtonGravar.setEnabled(false);
                    jButtonNovo.setEnabled(true);
                    jButtonCancelar.setEnabled(false);
                    jButtonAlterar.setEnabled(false);
            }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUsu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelDados;
    private javax.swing.JLabel jLabelId_inst;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JList<String> jListNomes;
    private javax.swing.JScrollPane jScrollPaneNomes;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldId_Usu;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldSenha;
    // End of variables declaration//GEN-END:variables
}
